import React, { useState } from 'react';
import { DecisionAnalysis } from '../types';
import { X, Copy, Check, Printer } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: DecisionAnalysis;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, analysis }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = () => {
    let md = `# The Tiebreaker: Decision Analysis Report\n\n`;
    md += `**Date:** ${new Date(analysis.createdAt).toLocaleDateString()}\n`;
    md += `**Decision Question:** ${analysis.decisionQuestion}\n`;
    if (analysis.userContext) {
      md += `**Context & Values:** ${analysis.userContext}\n`;
    }
    md += `\n---\n\n## Identified Options\n\n`;
    analysis.options.forEach((opt, i) => {
      md += `### Option ${i + 1}: ${opt.name}\n${opt.description}\n\n`;
    });

    md += `---\n\n## The Tiebreaker Verdict\n\n`;
    md += `> **"${analysis.verdict.recommendation}"**\n\n`;
    md += `*Primary Winner:* **${analysis.verdict.primaryWinnerName}** (Confidence: ${analysis.verdict.confidence})\n\n`;
    md += `**Summary Rationale:**\n${analysis.verdict.summaryRationale}\n\n`;
    md += `**The Mirror Gut-Check Question:**\n*"${analysis.verdict.gutCheckQuestion}"*\n\n`;

    md += `### Priority Pathways\n`;
    analysis.verdict.priorityBranches.forEach((b) => {
      md += `- **If your priority is ${b.priority}:** Choose **${b.recommendedOptionName}** — ${b.rationale}\n`;
    });

    md += `\n### Cognitive Traps & Blindspots\n`;
    analysis.verdict.hiddenBlindspots.forEach((b, i) => {
      md += `${i + 1}. ${b}\n`;
    });

    md += `\n---\n\n## Pros & Cons Breakdown\n\n`;
    analysis.prosCons.forEach((pc) => {
      md += `### ${pc.optionName} (*"${pc.tagline}"*)\n`;
      md += `**Pros:**\n`;
      pc.pros.forEach((p) => {
        md += `- [${p.impact.toUpperCase()}] ${p.text} (${p.category})\n`;
      });
      md += `**Cons:**\n`;
      pc.cons.forEach((c) => {
        md += `- [${c.impact.toUpperCase()}] ${c.text} (${c.category})\n`;
      });
      md += `\n`;
    });

    md += `---\n\n## Comparison Criteria Matrix\n\n`;
    analysis.comparisonTable.forEach((crit) => {
      md += `### ${crit.criterion} (Weight: ${crit.weight}x - ${crit.category})\n`;
      md += `${crit.description}\n`;
      analysis.options.forEach((opt) => {
        const sc = crit.scores[opt.id];
        md += `- **${opt.name}:** ${sc?.score ?? '-'}/10 — ${sc?.explanation ?? ''}\n`;
      });
      md += `\n`;
    });

    md += `---\n\n## SWOT Strategic Matrix\n\n`;
    analysis.swotAnalysis.forEach((sw) => {
      md += `### SWOT: ${sw.optionName}\n`;
      md += `- **Strengths:** ${sw.strengths.join('; ')}\n`;
      md += `- **Weaknesses:** ${sw.weaknesses.join('; ')}\n`;
      md += `- **Opportunities:** ${sw.opportunities.join('; ')}\n`;
      md += `- **Threats:** ${sw.threats.join('; ')}\n\n`;
    });

    md += `---\n*Generated by The Tiebreaker AI Assistant*`;
    return md;
  };

  const handleCopy = async () => {
    const text = generateMarkdown();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error('Failed to copy', e);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const markdownContent = generateMarkdown();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-xs p-4">
      <div className="flex h-[85vh] w-full max-w-2xl flex-col rounded-2xl bg-white shadow-2xl overflow-hidden border border-slate-200">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4">
          <div>
            <h2 className="font-serif text-lg font-bold text-slate-900">
              Export Decision Report
            </h2>
            <p className="text-xs text-slate-500">
              Copy complete formatted Markdown report or print directly.
            </p>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content area */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-50 font-mono text-xs text-slate-800 leading-relaxed whitespace-pre-wrap select-all">
          {markdownContent}
        </div>

        {/* Footer actions */}
        <div className="flex items-center justify-between border-t border-slate-200 px-6 py-4 bg-white">
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3.5 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"
          >
            <Printer className="h-3.5 w-3.5" />
            Print Report
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="rounded-lg border border-slate-200 px-3.5 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50"
            >
              Close
            </button>
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white hover:bg-slate-800"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-400" />
                  Copied to Clipboard!
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5 text-amber-400" />
                  Copy Markdown
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
